import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

import '../widgets/verified_name.dart';
import 'public_profile_screen.dart';

/// ============================================================================
/// CHATTªX — FEED NOTIFICATION SCREEN
/// ============================================================================
///
/// Displays notifications generated by the ChattªX Feed.
///
/// IMPORTANT:
/// This version intentionally does NOT use:
///
///   .orderBy('createdAt')
///
/// together with:
///
///   .where('recipientId')
///
/// because that can require a Firestore composite index.
///
/// Instead, notifications are fetched by recipientId and sorted locally.
/// This makes the notification screen much more reliable.
/// ============================================================================

class FeedNotificationScreen extends StatefulWidget {
  const FeedNotificationScreen({super.key});

  @override
  State<FeedNotificationScreen> createState() =>
      _FeedNotificationScreenState();
}

class _FeedNotificationScreenState
    extends State<FeedNotificationScreen> {
  // ==========================================================================
  // COLORS
  // ==========================================================================

  static const Color _background = Color(0xFF050816);
  static const Color _card = Color(0xFF080D1A);
  static const Color _surface = Color(0xFF0D1324);
  static const Color _border = Color(0xFF18243A);

  static const Color _purple = Color(0xFF7B2FF7);
  static const Color _brightPurple = Color(0xFFB026FF);
  static const Color _cyan = Color(0xFF00D9FF);

  static const Color _primaryText = Color(0xFFF5F7FF);
  static const Color _secondaryText = Color(0xFF9AA3B5);
  static const Color _mutedText = Color(0xFF68738A);

  // ==========================================================================
  // FIRESTORE
  // ==========================================================================

  final FirebaseFirestore _firestore =
      FirebaseFirestore.instance;

  // ==========================================================================
  // CURRENT USER
  // ==========================================================================

  User? get _currentUser =>
      FirebaseAuth.instance.currentUser;

  String? get _currentUid =>
      _currentUser?.uid;

  // ==========================================================================
  // BUILD
  // ==========================================================================

  @override
  Widget build(BuildContext context) {
    final uid = _currentUid;

    return Scaffold(
      backgroundColor: _background,
      appBar: AppBar(
        backgroundColor: _background,
        elevation: 0,
        centerTitle: false,
        titleSpacing: 16,
        title: ShaderMask(
          shaderCallback: (bounds) {
            return const LinearGradient(
              colors: [
                _primaryText,
                _brightPurple,
                _cyan,
              ],
            ).createShader(bounds);
          },
          child: const Text(
            'Notifications',
            style: TextStyle(
              color: Colors.white,
              fontSize: 24,
              fontWeight: FontWeight.w800,
              letterSpacing: -0.7,
            ),
          ),
        ),
        actions: [
          IconButton(
            tooltip: 'Mark all as read',
            onPressed: uid == null
                ? null
                : () => _markAllAsRead(uid),
            icon: const Icon(
              Icons.done_all_rounded,
              color: _secondaryText,
            ),
          ),
          const SizedBox(width: 4),
        ],
      ),
      body: uid == null
          ? _buildNotSignedIn()
          : _buildNotifications(uid),
    );
  }

  // ==========================================================================
  // NOT SIGNED IN
  // ==========================================================================

  Widget _buildNotSignedIn() {
    return const Center(
      child: Padding(
        padding: EdgeInsets.all(30),
        child: Text(
          'Sign in to see your notifications.',
          textAlign: TextAlign.center,
          style: TextStyle(
            color: _secondaryText,
            fontSize: 15,
          ),
        ),
      ),
    );
  }

  // ==========================================================================
  // NOTIFICATIONS
  // ==========================================================================

  Widget _buildNotifications(String uid) {
    return StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
      stream: _firestore
          .collection('feed_notifications')
          .where(
            'recipientId',
            isEqualTo: uid,
          )
          .limit(100)
          .snapshots(),
      builder: (context, snapshot) {
        // ----------------------------------------------------------------------
        // ERROR
        // ----------------------------------------------------------------------

        if (snapshot.hasError) {
          return _buildError(
            onRetry: () {
              setState(() {});
            },
          );
        }

        // ----------------------------------------------------------------------
        // LOADING
        // ----------------------------------------------------------------------

        if (snapshot.connectionState ==
                ConnectionState.waiting &&
            !snapshot.hasData) {
          return const Center(
            child: CircularProgressIndicator(
              color: _brightPurple,
            ),
          );
        }

        // ----------------------------------------------------------------------
        // DOCUMENTS
        // ----------------------------------------------------------------------

        final documents =
            List<QueryDocumentSnapshot<Map<String, dynamic>>>.from(
          snapshot.data?.docs ?? [],
        );

        // ----------------------------------------------------------------------
        // SORT LOCALLY
        //
        // This avoids requiring a Firestore composite index.
        // ----------------------------------------------------------------------

        documents.sort((a, b) {
          final aDate = _timestampFrom(
            a.data()['createdAt'],
          );

          final bDate = _timestampFrom(
            b.data()['createdAt'],
          );

          if (aDate == null && bDate == null) {
            return 0;
          }

          if (aDate == null) {
            return 1;
          }

          if (bDate == null) {
            return -1;
          }

          return bDate.compareTo(aDate);
        });

        // ----------------------------------------------------------------------
        // EMPTY
        // ----------------------------------------------------------------------

        if (documents.isEmpty) {
          return _buildEmpty();
        }

        // ----------------------------------------------------------------------
        // LIST
        // ----------------------------------------------------------------------

        return ListView.builder(
          physics: const BouncingScrollPhysics(),
          padding: const EdgeInsets.fromLTRB(
            8,
            4,
            8,
            30,
          ),
          itemCount: documents.length,
          itemBuilder: (context, index) {
            final document = documents[index];

            return _NotificationTile(
              key: ValueKey(document.id),
              document: document,
              onTap: () => _openNotification(document),
              onMarkRead: () => _markAsRead(document.id),
            );
          },
        );
      },
    );
  }

  // ==========================================================================
  // SAFE TIMESTAMP
  // ==========================================================================

  DateTime? _timestampFrom(dynamic value) {
    if (value is Timestamp) {
      return value.toDate();
    }

    if (value is DateTime) {
      return value;
    }

    if (value is String) {
      return DateTime.tryParse(value);
    }

    return null;
  }

  // ==========================================================================
  // EMPTY
  // ==========================================================================

  Widget _buildEmpty() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(30),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              width: 72,
              height: 72,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: const LinearGradient(
                  colors: [
                    _purple,
                    _brightPurple,
                  ],
                ),
                boxShadow: [
                  BoxShadow(
                    color:
                        _brightPurple.withValues(alpha: 0.25),
                    blurRadius: 25,
                    spreadRadius: 2,
                  ),
                ],
              ),
              child: const Icon(
                Icons.notifications_none_rounded,
                color: Colors.white,
                size: 36,
              ),
            ),
            const SizedBox(height: 18),
            const Text(
              'No notifications yet',
              style: TextStyle(
                color: _primaryText,
                fontSize: 18,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 7),
            const Text(
              'When people interact with your posts,\nyou will see it here.',
              textAlign: TextAlign.center,
              style: TextStyle(
                color: _secondaryText,
                fontSize: 14,
                height: 1.4,
              ),
            ),
          ],
        ),
      ),
    );
  }

  // ==========================================================================
  // ERROR
  // ==========================================================================

  Widget _buildError({
    required VoidCallback onRetry,
  }) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(30),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(
              Icons.cloud_off_rounded,
              color: _mutedText,
              size: 42,
            ),
            const SizedBox(height: 14),
            const Text(
              'Could not load notifications',
              style: TextStyle(
                color: _primaryText,
                fontSize: 16,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 7),
            const Text(
              'Something went wrong while loading your notifications.',
              textAlign: TextAlign.center,
              style: TextStyle(
                color: _secondaryText,
                fontSize: 13,
              ),
            ),
            const SizedBox(height: 18),
            TextButton.icon(
              onPressed: onRetry,
              icon: const Icon(
                Icons.refresh_rounded,
                color: _cyan,
              ),
              label: const Text(
                'Try again',
                style: TextStyle(
                  color: _cyan,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  // ==========================================================================
  // MARK ONE AS READ
  // ==========================================================================

  Future<void> _markAsRead(
    String notificationId,
  ) async {
    try {
      await _firestore
          .collection('feed_notifications')
          .doc(notificationId)
          .update({
        'isRead': true,
        'readAt': FieldValue.serverTimestamp(),
      });
    } catch (_) {
      // Keep notification screen stable.
    }
  }

  // ==========================================================================
  // MARK ALL AS READ
  // ==========================================================================

  Future<void> _markAllAsRead(
    String uid,
  ) async {
    try {
      final query = await _firestore
          .collection('feed_notifications')
          .where(
            'recipientId',
            isEqualTo: uid,
          )
          .where(
            'isRead',
            isEqualTo: false,
          )
          .limit(500)
          .get();

      if (query.docs.isEmpty) {
        return;
      }

      final batch = _firestore.batch();

      for (final document in query.docs) {
        batch.update(
          document.reference,
          {
            'isRead': true,
            'readAt': FieldValue.serverTimestamp(),
          },
        );
      }

      await batch.commit();
    } catch (_) {
      // Keep UI stable if batch update fails.
    }
  }

  // ==========================================================================
  // OPEN NOTIFICATION
  // ==========================================================================

  Future<void> _openNotification(
    QueryDocumentSnapshot<Map<String, dynamic>> document,
  ) async {
    final data = document.data();

    if (data['isRead'] != true) {
      await _markAsRead(document.id);
    }

    final actorId =
        (data['actorId'] ?? '').toString().trim();

    final profileId =
        (data['profileId'] ?? '').toString().trim();

    final targetId =
        (data['targetId'] ?? '').toString().trim();

    final destinationId =
        profileId.isNotEmpty
            ? profileId
            : actorId;

    if (!mounted) {
      return;
    }

    // ------------------------------------------------------------------------
    // PROFILE / FOLLOW NOTIFICATIONS
    // ------------------------------------------------------------------------

    if (destinationId.isNotEmpty &&
        (data['type'] == 'follow' ||
            data['type'] == 'newFollower' ||
            data['type'] == 'followRequest' ||
            data['type'] == 'followRequestAccepted' ||
            data['type'] == 'profileView')) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (_) => PublicProfileScreen(
            userId: destinationId,
          ),
        ),
      );

      return;
    }

    // ------------------------------------------------------------------------
    // CONTENT NOTIFICATIONS
    // ------------------------------------------------------------------------

    if (targetId.isNotEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(
            'This notification is linked to content.',
          ),
          duration: Duration(seconds: 2),
        ),
      );
    }
  }
}

// =============================================================================
// NOTIFICATION TILE
// =============================================================================

class _NotificationTile extends StatelessWidget {
  const _NotificationTile({
    super.key,
    required this.document,
    required this.onTap,
    required this.onMarkRead,
  });

  final QueryDocumentSnapshot<Map<String, dynamic>> document;

  final VoidCallback onTap;
  final VoidCallback onMarkRead;

  static const Color _card =
      Color(0xFF080D1A);

  static const Color _surface =
      Color(0xFF0D1324);

  static const Color _border =
      Color(0xFF18243A);

  static const Color _purple =
      Color(0xFF7B2FF7);

  static const Color _brightPurple =
      Color(0xFFB026FF);

  static const Color _cyan =
      Color(0xFF00D9FF);

  static const Color _primaryText =
      Color(0xFFF5F7FF);

  static const Color _secondaryText =
      Color(0xFF9AA3B5);

  @override
  Widget build(BuildContext context) {
    final data = document.data();

    final actorName =
        (data['actorName'] ?? 'Someone').toString();

    final actorPhoto =
        (data['actorPhoto'] ?? '')
            .toString()
            .trim();

    final actorId =
        (data['actorId'] ?? '')
            .toString()
            .trim();

    final type =
        (data['type'] ?? 'system').toString();

    final reaction =
        (data['reaction'] ?? '')
            .toString()
            .trim();

    final customMessage =
        (data['message'] ?? '')
            .toString()
            .trim();

    final isRead =
        data['isRead'] == true;

    final message = _messageFor(
      type: type,
      reaction: reaction,
      customMessage: customMessage,
      data: data,
    );

    final icon = _iconFor(type);

    return Padding(
      padding: const EdgeInsets.only(
        bottom: 6,
      ),
      child: Material(
        color: isRead
            ? _card
            : _surface,
        borderRadius:
            BorderRadius.circular(18),
        child: InkWell(
          borderRadius:
              BorderRadius.circular(18),
          onTap: () {
            if (!isRead) {
              onMarkRead();
            }

            onTap();
          },
          child: Container(
            padding: const EdgeInsets.symmetric(
              horizontal: 12,
              vertical: 11,
            ),
            decoration: BoxDecoration(
              borderRadius:
                  BorderRadius.circular(18),
              border: Border.all(
                color: isRead
                    ? _border
                    : _brightPurple.withValues(
                        alpha: 0.28,
                      ),
              ),
            ),
            child: Row(
              crossAxisAlignment:
                  CrossAxisAlignment.center,
              children: [
                _buildAvatar(actorPhoto),

                const SizedBox(width: 11),

                Expanded(
                  child: Column(
                    crossAxisAlignment:
                        CrossAxisAlignment.start,
                    children: [
                      _buildVerifiedActorName(
                        context: context,
                        actorId: actorId,
                        actorName: actorName,
                        message: message,
                      ),

                      const SizedBox(height: 5),

                      _buildTime(
                        data['createdAt'],
                      ),
                    ],
                  ),
                ),

                const SizedBox(width: 8),

                Container(
                  width: 34,
                  height: 34,
                  decoration: const BoxDecoration(
                    shape: BoxShape.circle,
                    gradient: LinearGradient(
                      colors: [
                        _purple,
                        _brightPurple,
                      ],
                    ),
                  ),
                  child: Icon(
                    icon,
                    color: Colors.white,
                    size: 17,
                  ),
                ),

                if (!isRead)
                  Container(
                    margin:
                        const EdgeInsets.only(left: 7),
                    width: 7,
                    height: 7,
                    decoration:
                        const BoxDecoration(
                      color: _cyan,
                      shape: BoxShape.circle,
                    ),
                  ),
              ],
            ),
          ),
        ),
      ),
    );
  }

// ==========================================================================
// VERIFIED ACTOR NAME + MESSAGE
// ==========================================================================
//
// Loads the actor's CURRENT verification status from:
//
// users/{actorId}
//
// and uses the SAME VerifiedName widget used throughout ChattªX.
//
// This keeps the blue ChattªX verification badge consistent with FeedScreen.
// ==========================================================================

Widget _buildVerifiedActorName({
  required BuildContext context,
  required String actorId,
  required String actorName,
  required String message,
}) {
  // ------------------------------------------------------------------------
  // No actor ID
  // ------------------------------------------------------------------------

  if (actorId.isEmpty) {
    return _buildNameAndMessage(
      actorName: actorName,
      message: message,
      verified: false,
    );
  }

  // ------------------------------------------------------------------------
  // Read the user's CURRENT verification status.
  // ------------------------------------------------------------------------

  return StreamBuilder<DocumentSnapshot<Map<String, dynamic>>>(
    stream: FirebaseFirestore.instance
        .collection('users')
        .doc(actorId)
        .snapshots(),
    builder: (context, snapshot) {
      bool verified = false;

      if (snapshot.hasData && snapshot.data!.exists) {
        final userData = snapshot.data!.data();

        verified = userData?['isVerified'] == true;
      }

      return _buildNameAndMessage(
        actorName: actorName,
        message: message,
        verified: verified,
      );
    },
  );
}

  // ==========================================================================
// NAME + MESSAGE
// ==========================================================================
//
// IMPORTANT:
// Do NOT put VerifiedName inside a RichText WidgetSpan.
//
// VerifiedName already contains its own Row containing:
//
//     Name + blue verification badge
//
// So we build the name and message as normal Flutter widgets.
// ==========================================================================

Widget _buildNameAndMessage({
  required String actorName,
  required String message,
  required bool verified,
}) {
  return Wrap(
    crossAxisAlignment: WrapCrossAlignment.center,
    children: [
      VerifiedName(
        name: actorName,
        verified: verified,
        fontSize: 14,
        fontWeight: FontWeight.w700,
        textColor: _primaryText,
      ),

      if (message.isNotEmpty) ...[
        const SizedBox(width: 4),
        Text(
          message,
          style: const TextStyle(
            color: _secondaryText,
            fontSize: 14,
            height: 1.35,
            fontWeight: FontWeight.w400,
          ),
        ),
      ],
    ],
  );
}

  // ==========================================================================
  // AVATAR
  // ==========================================================================

  Widget _buildAvatar(
    String photo,
  ) {
    if (photo.isEmpty) {
      return Container(
        width: 48,
        height: 48,
        decoration: const BoxDecoration(
          shape: BoxShape.circle,
          gradient: LinearGradient(
            colors: [
              _purple,
              _brightPurple,
            ],
          ),
        ),
        child: const Icon(
          Icons.person_rounded,
          color: Colors.white,
          size: 25,
        ),
      );
    }

    return ClipOval(
      child: Image.network(
        photo,
        width: 48,
        height: 48,
        fit: BoxFit.cover,
        errorBuilder:
            (context, error, stackTrace) {
          return Container(
            width: 48,
            height: 48,
            decoration:
                const BoxDecoration(
              shape: BoxShape.circle,
              gradient: LinearGradient(
                colors: [
                  _purple,
                  _brightPurple,
                ],
              ),
            ),
            child: const Icon(
              Icons.person_rounded,
              color: Colors.white,
              size: 25,
            ),
          );
        },
      ),
    );
  }

  // ==========================================================================
  // ICON
  // ==========================================================================

  IconData _iconFor(
    String type,
  ) {
    switch (type) {
      case 'like':
      case 'postLike':
      case 'videoLike':
      case 'commentLike':
        return Icons.favorite_rounded;

      case 'comment':
      case 'postComment':
      case 'videoComment':
      case 'pollComment':
        return Icons.chat_bubble_rounded;

      case 'share':
      case 'postShare':
      case 'videoShare':
        return Icons.share_rounded;

      case 'follow':
      case 'newFollower':
      case 'followRequest':
        return Icons.person_add_rounded;

      case 'followRequestAccepted':
        return Icons.check_circle_rounded;

      case 'unfollow':
        return Icons.person_remove_rounded;

      case 'reaction':
      case 'commentReaction':
      case 'storyReaction':
        return Icons.emoji_emotions_rounded;

      case 'save':
      case 'postSave':
        return Icons.bookmark_rounded;

      case 'reply':
      case 'storyReply':
        return Icons.reply_rounded;

      case 'mention':
        return Icons.alternate_email_rounded;

      case 'tag':
        return Icons.person_search_rounded;

      case 'pollVote':
        return Icons.poll_rounded;

      case 'liveStarted':
        return Icons.live_tv_rounded;

      case 'liveEnded':
        return Icons.stop_circle_rounded;

      case 'profileView':
        return Icons.visibility_rounded;

      case 'milestone':
        return Icons.emoji_events_rounded;

      default:
        return Icons.notifications_rounded;
    }
  }

  // ==========================================================================
  // MESSAGE
  // ==========================================================================

  String _messageFor({
    required String type,
    required String reaction,
    required String customMessage,
    required Map<String, dynamic> data,
  }) {
    if (customMessage.isNotEmpty) {
      return customMessage;
    }

    final targetType =
        (data['targetType'] ?? 'post').toString();

    String target = targetType;

    if (target == 'none') {
      target = 'post';
    }

    switch (type) {
      case 'like':
      case 'postLike':
      case 'videoLike':
        return 'liked your $target';

      case 'comment':
      case 'postComment':
      case 'videoComment':
        return 'commented on your $target';

      case 'share':
      case 'postShare':
      case 'videoShare':
        return 'shared your $target';

      case 'follow':
      case 'newFollower':
        return 'started following you';

      case 'unfollow':
        return 'unfollowed you';

      case 'mention':
        return 'mentioned you';

      case 'reaction':
      case 'commentReaction':
        if (reaction.isNotEmpty) {
          return 'reacted $reaction to your $target';
        }

        return 'reacted to your $target';

      case 'save':
      case 'postSave':
        return 'saved your $target';

      case 'reply':
        return 'replied to your comment';

      case 'commentLike':
        return 'liked your comment';

      case 'pollVote':
        return 'voted on your poll';

      case 'pollComment':
        return 'commented on your poll';

      case 'tag':
        return 'tagged you';

      case 'followRequest':
        return 'sent you a follow request';

      case 'followRequestAccepted':
        return 'accepted your follow request';

      case 'liveStarted':
        return 'started a live video';

      case 'liveEnded':
        return 'ended a live video';

      case 'storyReply':
        return 'replied to your story';

      case 'storyReaction':
        if (reaction.isNotEmpty) {
          return 'reacted $reaction to your story';
        }

        return 'reacted to your story';

      case 'profileView':
        return 'viewed your profile';

      case 'milestone':
        return 'reached a milestone';

      default:
        return 'sent you a notification';
    }
  }

  // ==========================================================================
  // TIME
  // ==========================================================================

  Widget _buildTime(
    dynamic value,
  ) {
    DateTime? date;

    if (value is Timestamp) {
      date = value.toDate();
    } else if (value is DateTime) {
      date = value;
    } else if (value is String) {
      date = DateTime.tryParse(value);
    }

    if (date == null) {
      return const Text(
        'Just now',
        style: TextStyle(
          color: _secondaryText,
          fontSize: 11,
        ),
      );
    }

    final now = DateTime.now();

    final difference =
        now.difference(date);

    String text;

    if (difference.inSeconds < 60) {
      text = 'Just now';
    } else if (difference.inMinutes < 60) {
      text = '${difference.inMinutes}m';
    } else if (difference.inHours < 24) {
      text = '${difference.inHours}h';
    } else if (difference.inDays < 7) {
      text = '${difference.inDays}d';
    } else {
      text =
          '${date.day}/${date.month}/${date.year}';
    }

    return Text(
      text,
      style: const TextStyle(
        color: _secondaryText,
        fontSize: 11,
        fontWeight: FontWeight.w500,
      ),
    );
  }
}